# -*- coding: utf-8 -*-
"""Copy of vl_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAdUNf6YzdPFWCZ20M9BhtP6olLEoaVP
"""

!pip install solidity-parser networkx matplotlib torch torch-geometric

import os
import torch
import networkx as nx
import matplotlib.pyplot as plt
from solidity_parser import parser

!git clone https://github.com/smartbugs/smartbugs-curated.git
!git clone https://github.com/DependableSystemsLab/SolidiFI-benchmark.git



print("SmartBugs sample folders:", os.listdir("smartbugs-curated")[:5])
print("SolidiFI sample folders:", os.listdir("SolidiFI-benchmark")[:5])

def collect_solidity_files(base, limit=4):
    files = []
    for root, _, fs in os.walk(base):
        for f in fs:
            if f.endswith(".sol"):
                files.append(os.path.join(root, f))
                if len(files) >= limit:
                    return files
    return files

smartbugs_files = collect_solidity_files("smartbugs-curated", 3)
solidifi_files = collect_solidity_files("SolidiFI-benchmark", 3)

contracts = smartbugs_files + solidifi_files
print("Contracts selected for analysis:")
for c in contracts:
    print(" •", c)

parsed_contracts = []

for c in contracts:
    try:
        ast = parser.parse_file(c)
        parsed_contracts.append((c, ast))
        print("Parsed:", c)
    except:
        print("Failed:", c)

print("Total successfully parsed:", len(parsed_contracts))

def ast_stats(ast):
    funcs = 0
    stmts = 0

    for node in ast.get("children", []):
        if node.get("type") == "ContractDefinition":
            for sub in node.get("subNodes", []):
                if sub.get("type") == "FunctionDefinition":
                    funcs += 1
                    body = sub.get("body")
                    if isinstance(body, dict):
                        stmts += len(body.get("statements", []))
                    elif isinstance(body, list):
                        stmts += len(body)
    return funcs, stmts

for path, ast in parsed_contracts:
    f, s = ast_stats(ast)
    print(f"\n{path}\nFunctions: {f}, Statements: {s}")

def swc_label(path):
    p = path.lower()
    if "reentrancy" in p:
        return "SWC-107 (Reentrancy)"
    if "access" in p:
        return "SWC-115 (Access Control)"
    if "transaction" in p or "tod" in p:
        return "SWC-114 (Transaction Order Dependency)"
    return "SWC-123 (State Inconsistency)"

def extract_call_graph(ast):
    g = nx.DiGraph()
    functions = {}

    for node in ast.get("children", []):
        if node.get("type") == "ContractDefinition":
            for sub in node.get("subNodes", []):
                if sub.get("type") == "FunctionDefinition":
                    fname = sub.get("name") or "fallback"
                    functions[fname] = sub
                    g.add_node(fname, node_type="function")

    for fname, fnode in functions.items():
        body = fnode.get("body")

        if isinstance(body, dict):
            stmts = body.get("statements", [])
        elif isinstance(body, list):
            stmts = body
        else:
            continue

        for stmt in stmts:
            if isinstance(stmt, dict) and stmt.get("type") == "ExpressionStatement":
                expr = stmt.get("expression", {})
                if expr.get("type") == "FunctionCall":
                    callee = expr.get("expression", {}).get("name")
                    if callee in functions:
                        g.add_edge(fname, callee)

    return g

def clean_labels(g):
    mapping = {}
    for n in g.nodes:
        if "function()" in n or "payable" in n:
            mapping[n] = "fallback"
        elif len(n) > 20:
            mapping[n] = n[:17] + "..."
    return nx.relabel_nodes(g, mapping)

def draw_call_graph(g, title):
    plt.figure(figsize=(8, 6))

    # Choose layout dynamically
    if g.number_of_nodes() <= 5:
        pos = nx.spring_layout(g, seed=42, k=1.8)
    elif g.number_of_nodes() <= 12:
        pos = nx.kamada_kawai_layout(g)
    else:
        pos = nx.spring_layout(g, seed=42, k=2.5)

    nx.draw_networkx_nodes(
        g, pos,
        node_color="#AED6F1",
        node_size=1800,
        alpha=0.9
    )

    nx.draw_networkx_edges(
        g, pos,
        arrows=True,
        arrowstyle="->",
        arrowsize=15,
        edge_color="gray",
        width=1.5
    )

    nx.draw_networkx_labels(
        g, pos,
        font_size=8,
        font_weight="bold"
    )

    plt.title(title, fontsize=12)
    plt.axis("off")
    plt.tight_layout()
    plt.show()

for path, ast in parsed_contracts:
    g = extract_call_graph(ast)
    g = clean_labels(g)

    print("\n" + "="*60)
    print("Contract:", path)
    print("SWC Label:", swc_label(path))
    print("Number of Functions:", g.number_of_nodes())
    print("Cross-Function Calls:", g.number_of_edges())

    if g.number_of_edges() > 0:
        print("Call Relationships:")
        for u, v in g.edges:
            print(f"  {u}  →  {v}")
    else:
        print("Call Relationships: None")

    draw_call_graph(g, "Function Call Graph (Cross-Function)")

def extract_cfg(ast):
    cfg = nx.DiGraph()
    idx = 0

    for node in ast.get("children", []):
        if node.get("type") == "ContractDefinition":
            for sub in node.get("subNodes", []):
                if sub.get("type") == "FunctionDefinition":
                    prev = None
                    body = sub.get("body")

                    if isinstance(body, dict):
                        stmts = body.get("statements", [])
                    elif isinstance(body, list):
                        stmts = body
                    else:
                        continue

                    for stmt in stmts:
                        curr = f"stmt_{idx}"
                        cfg.add_node(curr, node_type="statement")
                        if prev:
                            cfg.add_edge(prev, curr, edge_type="control")
                        prev = curr
                        idx += 1
    return cfg

cfg = extract_cfg(parsed_contracts[0][1])

plt.figure(figsize=(6,4))
pos = nx.spring_layout(cfg, seed=1)
nx.draw(
    cfg, pos,
    with_labels=True,
    node_color="#F9E79F",
    node_size=1600,
    font_size=8
)
plt.title("Control Flow Graph (CFG)")
plt.show()

print("CFG Nodes:", cfg.number_of_nodes())
print("CFG Edges:", cfg.number_of_edges())

def merge_graphs(call_g, cfg):
    h = nx.DiGraph()

    for g in [call_g, cfg]:
        for n, a in g.nodes(data=True):
            h.add_node(n, **a)
        for u, v, a in g.edges(data=True):
            h.add_edge(u, v, **a)

    return h

def clean_hcpg_labels(h):
    mapping = {}
    for n in h.nodes:
        if isinstance(n, str) and "function()" in n:
            mapping[n] = "fallback"
        elif isinstance(n, str) and len(n) > 20:
            mapping[n] = n[:17] + "..."
    return nx.relabel_nodes(h, mapping)

def draw_hcpg(h):
    plt.figure(figsize=(9, 6))

    # Stronger spacing for heterogeneous graph
    pos = nx.spring_layout(h, seed=10, k=2.8)

    function_nodes = []
    stmt_nodes = []

    for n, a in h.nodes(data=True):
        if a.get("node_type") == "function":
            function_nodes.append(n)
        else:
            stmt_nodes.append(n)

    # Draw function nodes
    nx.draw_networkx_nodes(
        h, pos,
        nodelist=function_nodes,
        node_color="#85C1E9",
        node_size=2000,
        label="Function Nodes"
    )

    # Draw statement nodes
    nx.draw_networkx_nodes(
        h, pos,
        nodelist=stmt_nodes,
        node_color="#F7DC6F",
        node_size=1000,
        label="Statement Nodes"
    )

    # Draw edges
    nx.draw_networkx_edges(
        h, pos,
        edge_color="gray",
        arrows=True,
        arrowsize=12,
        width=1.2
    )

    # Draw labels
    nx.draw_networkx_labels(
        h, pos,
        font_size=7
    )

    plt.title("Partial Heterogeneous Code Property Graph", fontsize=12)
    plt.legend(scatterpoints=1)
    plt.axis("off")
    plt.tight_layout()
    plt.show()

call_g = extract_call_graph(parsed_contracts[0][1])
cfg = extract_cfg(parsed_contracts[0][1])

hcpg = merge_graphs(call_g, cfg)
hcpg = clean_hcpg_labels(hcpg)

draw_hcpg(hcpg)









def draw_call_graph(g, title):
    plt.figure(figsize=(8, 6))

    # Choose layout based on size
    if g.number_of_nodes() <= 6:
        pos = nx.spring_layout(g, seed=42, k=1.5)
    else:
        pos = nx.kamada_kawai_layout(g)

    nx.draw_networkx_nodes(
        g, pos,
        node_size=1800,
        node_color="#AED6F1",
        alpha=0.9
    )

    nx.draw_networkx_edges(
        g, pos,
        arrows=True,
        arrowstyle='-|>',
        arrowsize=15,
        edge_color="gray",
        width=1.5
    )

    nx.draw_networkx_labels(
        g, pos,
        font_size=8,
        font_weight="bold"
    )

    plt.title(title, fontsize=12)
    plt.axis("off")
    plt.tight_layout()
    plt.show()

g = extract_call_graph(ast)
draw_call_graph(g, "Function Call Graph (Cross-Function)")

def draw_cfg(cfg):
    plt.figure(figsize=(9, 5))

    pos = nx.shell_layout(cfg)

    nx.draw(
        cfg, pos,
        with_labels=True,
        node_color="#F9E79F",
        node_size=1200,
        font_size=7,
        edge_color="black",
        arrows=True
    )

    plt.title("Control Flow Graph (CFG)", fontsize=12)
    plt.axis("off")
    plt.tight_layout()
    plt.show()

    print("CFG Nodes:", cfg.number_of_nodes())
    print("CFG Edges:", cfg.number_of_edges())

def draw_hcpg(hcpg):
    plt.figure(figsize=(9, 6))

    pos = nx.spring_layout(hcpg, seed=10, k=2.0)

    function_nodes = [n for n in hcpg.nodes if not str(n).startswith("stmt")]
    stmt_nodes = [n for n in hcpg.nodes if str(n).startswith("stmt")]

    nx.draw_networkx_nodes(
        hcpg, pos,
        nodelist=function_nodes,
        node_color="#85C1E9",
        node_size=1800,
        label="Functions"
    )

    nx.draw_networkx_nodes(
        hcpg, pos,
        nodelist=stmt_nodes,
        node_color="#F7DC6F",
        node_size=1000,
        label="Statements"
    )

    nx.draw_networkx_edges(
        hcpg, pos,
        edge_color="gray",
        arrows=True,
        arrowsize=12
    )

    nx.draw_networkx_labels(
        hcpg, pos,
        font_size=7
    )

    plt.title("Partial Heterogeneous Code Property Graph", fontsize=12)
    plt.legend(scatterpoints=1)
    plt.axis("off")
    plt.tight_layout()
    plt.show()

def shorten_labels(g):
    mapping = {}
    for n in g.nodes:
        if "function()" in n:
            mapping[n] = "fallback"
        elif len(n) > 18:
            mapping[n] = n[:15] + "..."
    return nx.relabel_nodes(g, mapping)

g = shorten_labels(g)
draw_call_graph(g, "Function Call Graph (Cross-Function)")